# Generated by Django 5.2.10 on 2026-01-30 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('solar_panel', 'Solar Panel'), ('battery', 'Battery'), ('electric_vehicle', 'Electric Vehicle'), ('appliance', 'Appliance')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('properties', models.JSONField(default=dict)),
                ('current_state', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_type', 'is_active'], name='core_device_device__77f354_idx'), models.Index(fields=['is_active', 'created_at'], name='core_device_is_acti_a9c036_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='core_item_name_de2dec_idx'), models.Index(fields=['is_active', 'created_at'], name='core_item_is_acti_4548d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_item_per_category')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('power_watts', models.FloatField()),
                ('charge_wh', models.FloatField(blank=True, null=True)),
                ('state_snapshot', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='core.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='core_teleme_device__00746c_idx'), models.Index(fields=['timestamp'], name='core_teleme_timesta_fb8d19_idx'), models.Index(fields=['device', '-timestamp'], name='core_teleme_device__6fd47f_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'timestamp'), name='unique_device_timestamp')],
            },
        ),
    ]
